"""Hardcoded order records.

This module is the only place that knows how order data is stored. It
exposes a single lookup surface (ORDERS plus the helper functions in
tools.py) so that swapping this in-memory dict for a real order-management
API later only requires changing this module.
"""

from __future__ import annotations

from typing import Any

ORDERS: dict[str, dict[str, Any]] = {
    "CS-2026-100482": {
        "order_number": "CS-2026-100482",
        "customer_name": "Hannaford Supermarkets #214",
        "customer_account": "ACC-48831",
        "purchase_order_number": "PO-773421",
        "status": "RECEIVED",
        "status_description": "Order received and awaiting warehouse allocation.",
        "order_date": "2026-09-06",
        "promised_delivery_date": "2026-09-10",
        "actual_delivery_date": None,
        "distribution_center": "Hatfield, MA DC",
        "carrier": None,
        "tracking_number": None,
        "line_item_count": 42,
        "total_cases": 618,
        "exception_reason": None,
    },
    "CS-2026-100519": {
        "order_number": "CS-2026-100519",
        "customer_name": "Big Y Foods #087",
        "customer_account": "ACC-51290",
        "purchase_order_number": "PO-774108",
        "status": "PICKING",
        "status_description": "Order is being picked in the warehouse.",
        "order_date": "2026-09-06",
        "promised_delivery_date": "2026-09-09",
        "actual_delivery_date": None,
        "distribution_center": "Brattleboro, VT DC",
        "carrier": None,
        "tracking_number": None,
        "line_item_count": 61,
        "total_cases": 892,
        "exception_reason": None,
    },
    "CS-2026-100547": {
        "order_number": "CS-2026-100547",
        "customer_name": "Price Chopper #156",
        "customer_account": "ACC-33217",
        "purchase_order_number": "PO-774355",
        "status": "STAGED",
        "status_description": "Order picked and staged in the outbound dock, awaiting carrier pickup.",
        "order_date": "2026-09-05",
        "promised_delivery_date": "2026-09-08",
        "actual_delivery_date": None,
        "distribution_center": "Hatfield, MA DC",
        "carrier": "C&S Fleet Services",
        "tracking_number": None,
        "line_item_count": 38,
        "total_cases": 504,
        "exception_reason": None,
    },
    "CS-2026-100563": {
        "order_number": "CS-2026-100563",
        "customer_name": "Tops Friendly Markets #029",
        "customer_account": "ACC-60142",
        "purchase_order_number": "PO-774509",
        "status": "IN_TRANSIT",
        "status_description": "Order has left the distribution center and is en route to the store.",
        "order_date": "2026-09-04",
        "promised_delivery_date": "2026-09-08",
        "actual_delivery_date": None,
        "distribution_center": "Newburgh, NY DC",
        "carrier": "Estes Express Lines",
        "tracking_number": "EXL9928374615",
        "line_item_count": 55,
        "total_cases": 731,
        "exception_reason": None,
    },
    "CS-2026-100401": {
        "order_number": "CS-2026-100401",
        "customer_name": "ShopRite of Hillside",
        "customer_account": "ACC-19558",
        "purchase_order_number": "PO-772980",
        "status": "DELIVERED",
        "status_description": "Order delivered and signed for at the receiving dock.",
        "order_date": "2026-09-01",
        "promised_delivery_date": "2026-09-05",
        "actual_delivery_date": "2026-09-05",
        "distribution_center": "Robesonia, PA DC",
        "carrier": "C&S Fleet Services",
        "tracking_number": "CSF1123847",
        "line_item_count": 47,
        "total_cases": 663,
        "exception_reason": None,
    },
    "CS-2026-100388": {
        "order_number": "CS-2026-100388",
        "customer_name": "Market Basket #71",
        "customer_account": "ACC-27704",
        "purchase_order_number": "PO-772811",
        "status": "EXCEPTION",
        "status_description": "Delivery exception reported; order is on hold pending resolution.",
        "order_date": "2026-08-31",
        "promised_delivery_date": "2026-09-04",
        "actual_delivery_date": None,
        "distribution_center": "Hatfield, MA DC",
        "carrier": "Estes Express Lines",
        "tracking_number": "EXL9917732204",
        "line_item_count": 29,
        "total_cases": 412,
        "exception_reason": "Carrier reported a damaged pallet; awaiting replacement stock allocation.",
    },
    "CS-2026-100275": {
        "order_number": "CS-2026-100275",
        "customer_name": "Stop & Shop #303",
        "customer_account": "ACC-08853",
        "purchase_order_number": "PO-771642",
        "status": "CANCELLED",
        "status_description": "Order was cancelled at the customer's request prior to picking.",
        "order_date": "2026-08-27",
        "promised_delivery_date": "2026-08-31",
        "actual_delivery_date": None,
        "distribution_center": "Newburgh, NY DC",
        "carrier": None,
        "tracking_number": None,
        "line_item_count": 18,
        "total_cases": 240,
        "exception_reason": "Customer requested cancellation due to a duplicate purchase order.",
    },
}
